phpmyadmin:
   image: corbinu/docker-phpmyadmin
   ports :
    - "8080:80"
   environment:
    - MYSQL_USERNAME=root
    - MYSQL_PASSWORD=123456789
   links:
    - database:mysql
database:
  image: mysql:5.5
  ports:
   - "3306:3306"
  environment:
     - MYSQL_ROOT_PASSWORD=123456789
     - MYSQL_DATABASE=camagru
     - MYSQL_USER=camagru_user
     - MYSQL_PASSWORD=123456